source ' https://rubygems.org'
ruby '2.1.2'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-simple-authentication', :github => 'jshawl/sinatra-simple-authentication', :branch => 'master'
gem 'kronic'
gem 'pg'