require_relative '../app.rb'

Question.delete_all

	questions = Question.create(
		[
			{question: "What is the supreme law of the land?", wrong_answer_one: "Declaration of Independence", wrong_answer_two: "Federalist Papers"},
			{question: "What does the Constitution do?", wrong_answer_one: "Sets trade policy", wrong_answer_two: "Defines land ownership"},
			{question: "The idea of self-government is in the first three words of the Constitution.  What are these words?", wrong_answer_one: "Trusting in God", wrong_answer_two: "The people do"},
			{question: "What is an amendment?", wrong_answer_one: "A change or addition to the Federalist Papers.", wrong_answer_two: "A change or addition to the Declaration of Independence."},
			{question: "What do we call the first ten amendments to the Constitution?", wrong_answer_one: "The Ten Commandments", wrong_answer_two: "The First Ten"},
			{question: "What is one right or freedeom from the First Amendment?", wrong_answer_one: "Bear Arms", wrong_answer_two: "Own Land"},
			{question: "How many amendments does the Constitution have?", wrong_answer_one: "Twenty-five (25)", wrong_answer_two: "Thirty (30)"},
			{question: "What did the Declaration of Independence do?", wrong_answer_one: "Set up the government.", wrong_answer_two: "Freed the slaves."},
			{question: "What are two rights in the Declaration of Independence?", wrong_answer_one: "Love", wrong_answer_two: "Pursuit of wealth"},
			{question: "What is freedom of religion?", wrong_answer_one: "The government sanctions a particular religion.", wrong_answer_two: "Religion is taught in public schools."},
			{question: "What is the economic system in the United States?", wrong_answer_one: "Socialist economy", wrong_answer_two: "Libertarian economy"},
			{question: "What is the 'rule of law'?", wrong_answer_one: "The military determines laws.", wrong_answer_two: "A law textbook."},
			{question: "Name one branch or part of the government.", wrong_answer_one: "Council / Board", wrong_answer_two: "Parliament"},
			{question: "What stops one branch of government from becoming too powerful?", wrong_answer_one: "Strong military.", wrong_answer_two: "The Declaration of Independence"},
			{question: "Who is in charge of the executive branch?", wrong_answer_one: "The Prime Minister", wrong_answer_two: "The Governor"},
			{question: "Who makes federal laws?", wrong_answer_one: "Parliament", wrong_answer_two: "The President"},
			{question: "What are the two parts of the U.S. Congress?", wrong_answer_one: "The Lower House and Upper House", wrong_answer_two: "The House of Lords and the House of Commons"},
			{question: "How many U.S. Senators are there?", wrong_answer_one: "Fifty (50)", wrong_answer_two: "Two hundred (200)"},
			{question: "We elect a U.S. Senator for how many years?", wrong_answer_one: "Two (2)", wrong_answer_two: "Four (4)"},
			{question: "The House of Representatives has how many voting members?", wrong_answer_one: "One hundred (100)", wrong_answer_two: "Fifty (50)"},
			{question: "We elect a U.S. Representative for how many years?", wrong_answer_one: "Four (4)", wrong_answer_two: "Six (6)"}
			{question: "Name your U.S. Representative.", wrong_answer_one: nil, wrong_answer_two: nil},
			{question: "Who is one of your U.S. Senators now?", wrong_answer_one: nil, wrong_answer_two: nil},
			{question: "Who does a U.S. Senator represent?", wrong_answer_one: "Everyone in his/her district.", wrong_answer_two: "The entire nation."},
			{question: "Why do some states have more Representatives than other states?", wrong_answer_one: "Because of the state's wealth - More money means more representatives.", wrong_answer_two: "Because of the state's age - Older states have more representation"},
			{question: "We elect a President for how many years?", wrong_answer_one: "Six (6)", wrong_answer_two: "Two (2)"},
			{question: "In what month do we vote for President?", wrong_answer_one: "December", wrong_answer_two: "October"},
			{question: "What is the name of the President of the United States now?", wrong_answer_one: "George W Bush", wrong_answer_two: "Bill Clinton"},
			{question: "What is the name of the Vice President of the United States now?", wrong_answer_one: "Barack Obama", wrong_answer_two: "Hillary Clinton"},
			{question: "If the President can no longer serve, who becomes President?", wrong_answer_one: "The Speaker of the House", wrong_answer_two: "The First Lady"},
			{question: "If both the President and the Vice President can no longer serve, who becomes President?", wrong_answer_one: "The First Lady", wrong_answer_two: "Attorney General"},
			{question: "Who is the Commander in Chief of the military?", wrong_answer_one: "The Vice President", wrong_answer_two: "The Prime Minister"},
			{question: "Who signs bills to become laws?", wrong_answer_one: "The Prime Minister", wrong_answer_two: "The Speaker of the House"},
			{question: "Who vetoes bills?", wrong_answer_one: "The Vice President", wrong_answer_two: "The Speaker of the House"},
			{question: "What does the President's Cabinet do?", wrong_answer_one: "House the President's dishes", wrong_answer_two: "Protects the President"},
			{question: "What are two Cabinet-level positions?", wrong_answer_one: "Secretary of Letters", wrong_answer_two: "Secretary of Sport"},
			{question: "What does the judicial branch do?", wrong_answer_one: "Write laws", wrong_answer_two: "Enforce laws"},
			{question: "What is the highest court in the United States?", wrong_answer_one: "The Federal Court", wrong_answer_two: "The Court"},
			{question: "How many justices are on the Supreme Court?", wrong_answer_one: "Seven (7)", wrong_answer_two: "Eleven (11)"},
			{question: "Who is the Chief Justice of the United States now?", wrong_answer_one: "Antonin Scalia", wrong_answer_two: "Elena Kagan"},
			{question: "Under our Constitution, some powers belong to the federal government.  What is one power of the federal government?", wrong_answer_one: "Provide safety (fire departments", wrong_answer_two: "Provide schooling and education"},
			{question: "Under our Constitution, some powers belong to states.  What is one power of the states?", wrong_answer_one: "To print money", wrong_answer_two: "To make treaties"},
			{question: "Who is the Governor of your state now?", wrong_answer_one: nil, wrong_answer_two: nil},
			{question: "What is the capital of your state?", wrong_answer_one: nil, wrong_answer_two: nil},
			{question: "What are the two major political parties in the United States?", wrong_answer_one: "Green", wrong_answer_two: "Liberterian"},
			{question: "What is the political party of the President now?", wrong_answer_one: "Republican", wrong_answer_two: "Socialist"},
			{question: "What is the name of the Speaker of the House of Representatives now?", wrong_answer_one: nil, wrong_answer_two: nil},
			{question: "There are four amendments to the Constitution about who can vote.  Describe one of them.", wrong_answer_one: "Citzens fourteen (14) and older can vote.", wrong_answer_two: "Undocumented immigrants may vote."},
			{question: "What is one responsibility that is only for United States citizens?", wrong_answer_one: "Owning property.", wrong_answer_two: "Serving in the military."},
			{question: "Name one right only for United States citizens.", wrong_answer_one: "Owning land.", wrong_answer_two: "Free speech."},
			{question: "What are two rights of everyone living in the United States?", wrong_answer_one: "Freedom of Wealth", wrong_answer_two: "Right to Shelter"},
			{question: "What do we show loyalty to when we say the Pledge of Allegiance?", wrong_answer_one: "The President", wrong_answer_two: "The Military"},
			{question: "What is one promise you make when you become a United States citizen?", wrong_answer_one: "Pay taxes.", wrong_answer_two: "Buy land."},
			{question: "How old do citizens have to be to vote for President?", wrong_answer_one: "Fourteen (14).", wrong_answer_two: "Twenty-one (21)"},
			{question: "What are two ways that Americans can participate in their democracy?", wrong_answer_one: "Serve in the Military.", wrong_answer_two: "Own a business."},
			{question: "When is the last day you can send in federal income tax forms?", wrong_answer_one: "April 1", wrong_answer_two: "May 15"},
			{question: "When must all men register for the Selective Service?", wrong_answer_one: "Between sixteen (16) and eighteen (18)", wrong_answer_two: "Between twenty-six (26) and thirty (30)"},
			{question: "What is one reason colonists came to America?", wrong_answer_one: "Integrate with American Indians.", wrong_answer_two: "Find a shorter route to China."},
			{question: "Who lived in America before the Europeans arrived?", wrong_answer_one: "Chinese", wrong_answer_two: "Africans"},
			{question: "What group of people was taken to America and sold as slaves?", wrong_answer_one: "Arabs", wrong_answer_two: "Norwegians"},
			{question: "Why did the colonists fight the British?", wrong_answer_one: "To free the slaves.", wrong_answer_two: "To end the British Empire."},
			{question: "Who wrote the Declaration of Independence?", wrong_answer_one: "George Washington", wrong_answer_two: "Abraham Lincoln"},
			{question: "When was the Declaration of Independence adopted?", wrong_answer_one: "1861", wrong_answer_two: "1492"},
			{question: "There were 13 original states.  Name three.", wrong_answer_one: "Michigan", wrong_answer_two: "Florida"},
			{question: "What happened at the Constitutional Convention?", wrong_answer_one: "The Founding Fathers wrote the Federalist Papers", wrong_answer_two: "The Founding Fathers wrote the Declaration of Independence"},
			
		]
	
